/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function highlight(code: string): string
export interface HastProperties {
  className: string
}
export interface HastNode {
  type: string
  tagName: string
  properties: HastProperties
  children: Array<HastNode | HastTextNode>
}
export interface HastTextNode {
  type: string
  value: string
}
export function highlightHast(code: string): HastNode
